name: Checker

run-name: ${{ github.actor }} is building action
on: pull_request

jobs:

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Code style checker
        run: flake8 icmpflood/ --config .flake8 --show-source --statistics

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    needs: [ flake8 ]
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint --rcfile=pylintrc.cfg --output=pylint.log $(find $PWD/icmpflood -name "*.py" | xargs)
  pydoc:
    name: Pydoc
    runs-on: ubuntu-latest
    needs: [ pylint ]
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdoc3
      - name: Pydoc generation
        run: |
          pdoc3 --force --html --output-dir docs icmpflood
