name: Creating Release

run-name: ${{ github.actor }} is building action

on:
  push:
    branches:
      - 'release/**'

jobs:

  create-release:
    name: Create release
    runs-on: ubuntu-latest

    outputs:
      version_output: ${{ steps.version.outputs.project_version }}
      upload_url_output: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@v2

      - name: Project version
        id: version
        run: echo "project_version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          body_path: CHANGELOG
          tag_name: icmpflood-${{ steps.version.outputs.project_version }}
          release_name: icmpflood-${{ steps.version.outputs.project_version }}

  linux-build:
    name: Linux build
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        id: python-setup
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdoc3

      - name: Pydoc generation
        run: |
          pdoc3 --force --html --output-dir docs icmpflood

      - name: Create archive
        id: archive
        uses: vimtor/action-zip@5f1c4aa587ea41db1110df6a99981dbe19cee310
        with:
          files: .
          dest: icmpflood-docs-${{ needs.create-release.outputs.version_output }}.zip
          recursive: true

      - name: Upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url_output }}
          asset_name: icmpflood-docs-${{ needs.create-release.outputs.version_output }}.zip
          asset_path: ./icmpflood-docs-${{ needs.create-release.outputs.version_output }}.zip
          asset_content_type: application/zip
